version: "3.9"
services:
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: msvc-cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
# Uncomment and configure your application services if needed
  msvc-cursos:
    container_name: msvc-cursos
    image: cursos
    build:
      context: ./
      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file: ./msvc-cursos/.env
    environment:
      DB_HOST: postgres14
      DB_PORT: 5432
      DB_DATABASE_NAME: msvc-cursos
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      #USUARIOS_URL: ec2-54-172-173-52.compute-1.amazonaws.com:8001
      USUARIOS_URL: msvc-usuarios:8001
    networks:
      - spring
    depends_on:
      - postgres14
    restart: always
volumes:
  data-postgres:
    name: data-postgres
networks:
  spring:
    name: spring
