version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: msvc-usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    #restart: always
    networks:
      - spring
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: msvc-cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    #restart: always
    networks:
      - spring
# Uncomment and configure your application services if needed
  msvc-usuarios:
   container_name: msvc-usuarios
   image: usuarios
   build:
     context: ./
     dockerfile: ./msvc-usuarios/Dockerfile
   ports:
     - "8001:8001"
   env_file: ./msvc-usuarios/.env
   environment:
     DB_HOST: mysql8
     DB_PORT: 3306
     DB_DATABASE_NAME: msvc-usuarios
     DB_USERNAME: root
     DB_PASSWORD: password
     CURSOS_URL=msvc-cursos: 8002
   networks:
     - spring
   depends_on:
     - mysql8
   #restart: always
  msvc-cursos:
    container_name: msvc-cursos
    image: cursos
    build:
      context: ./
      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file: ./msvc-cursos/.env
    environment:
      DB_HOST: postgres14
      DB_PORT: 5432
      DB_DATABASE_NAME: msvc-cursos
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      USUARIOS_URL: msvc-usuarios:8001
    networks:
      - spring
    depends_on:
      - postgres14
      - msvc-usuarios
    #restart: always
volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres
networks:
  spring:
    name: spring
